#!/usr/bin/env python3
"""Import a DeepSeek Harness session export into a ZCode profile.

    python zcode_migrate.py inspect  <export.zip|dir>
    python zcode_migrate.py convert  <export.zip|dir> --session <sess_id> [--commit]
    python zcode_migrate.py convert  <export.zip|dir> --new-session [--commit]
    python zcode_migrate.py verify   <sess_id>
    python zcode_migrate.py rollback <sess_id> [--purge|--list-backups]

Without --commit every command is read-only: `convert` prints what it would write
and leaves a preview file behind. `rollback` deletes only the rows this tool
created (ids start with `msg_mig` / `part_mig`), or restores a snapshot with
`--purge`.

Run `python zcode_migrate.py --help` for the full flag list.
"""
from __future__ import annotations

import argparse
import collections
import json
import os
import re
import sys
import time
import uuid

import zcode_common as common
import zcode_live as live
import zcode_map as tmap

# ── fidelity presets ────────────────────────────────────────────────────────
# name: (tail_n, hist_args, hist_out, hist_text, hist_reason,
#        tail_args, tail_out, tail_text, tail_reason, err, synth)
# The `tail_n` most recent steps keep the `tail_*` budgets; older ones use `hist_*`.
PRESETS = {
    'lean':     (20, 150, 220, 250, 0, 2500, 3500, 4500, 700, 700, 1200),
    'balanced': (35, 260, 420, 450, 0, 4000, 5500, 7000, 1200, 900, 1600),
    'rich':     (60, 600, 1000, 1200, 200, 7000, 10000, 14000, 2500, 1500, 2500),
    'full':     (200, 2000, 4000, 4000, 800, 20000, 30000, 40000, 6000, 4000, 6000),
    # Deliberately small: leaves headroom for the next live turn.
    'resume':   (18, 120, 160, 200, 0, 2200, 3200, 4000, 600, 400, 900),
}
# Bulk results a later turn can just re-fetch; kept as a stub when not recent.
STUB_TOOLS = {'Skill': 260, 'Read': 400}

KIND_SEMANTICS = {
    'user': {'kind': 'user_prompt', 'origin': 'real_user', 'ui': 'visible',
             'provider': 'visible', 'transcript': 'visible'},
    'compact-checkpoint': {'kind': 'compact_summary', 'origin': 'agent_runtime', 'ui': 'hidden',
                           'provider': 'visible', 'transcript': 'hidden'},
    'agent-instructions': {'kind': 'system_reminder', 'origin': 'agent_runtime', 'ui': 'hidden',
                           'provider': 'visible', 'transcript': 'hidden'},
    'skill-catalog': {'kind': 'system_reminder', 'origin': 'agent_runtime', 'ui': 'hidden',
                      'provider': 'visible', 'transcript': 'hidden'},
    'runtime-context': {'kind': 'system_reminder', 'origin': 'agent_runtime', 'ui': 'hidden',
                        'provider': 'visible', 'transcript': 'hidden'},
    'model-selection': {'kind': 'system_reminder', 'origin': 'agent_runtime', 'ui': 'visible',
                        'provider': 'visible', 'transcript': 'visible'},
    'tool-jobs': {'kind': 'background_notification', 'origin': 'agent_runtime', 'ui': 'hidden',
                  'provider': 'visible', 'transcript': 'hidden'},
    'agent-message': {'kind': 'system_reminder', 'origin': 'agent_runtime', 'ui': 'hidden',
                      'provider': 'visible', 'transcript': 'hidden'},
    'subagent-settled': {'kind': 'subagent_notification', 'origin': 'agent_runtime', 'ui': 'hidden',
                         'provider': 'visible', 'transcript': 'hidden'},
}
# Carriers worth keeping; the rest are re-generated by ZCode on the next request
# and would only duplicate what the runtime already injects.
IMPORT_USER_KINDS = {'user', 'tool-jobs', 'model-selection'}

ENV_INFO = {
    "platform": "win32", "shell": "Git Bash", "osVersion": "win32 10.0.26200 x64",
    "nodeVersion": "v24.14.0", "isGitRepository": False, "gitStatus": "not_repo",
}


# ── text helpers ────────────────────────────────────────────────────────────
def clamp(s, n):
    s = s or ''
    if n <= 0:
        return ''
    if len(s) <= n:
        return s
    head = s[: int(n * 0.7)]
    tail = s[-int(n * 0.2):]
    return '%s\n…[%d chars elided on import]…\n%s' % (head, len(s) - len(head) - len(tail), tail)


def shrink_input(obj, budget):
    """Bound a tool input without ever changing its key set.

    The transcript is replayed to the provider against the declared tool schema,
    so a substituted placeholder object would make the request invalid. Only
    string values are shortened, and the key set survives at every step.
    """
    if len(json.dumps(obj, ensure_ascii=False)) <= budget:
        return obj, False

    def clip(x, per):
        if isinstance(x, dict):
            return {k: clip(v, per) for k, v in x.items()}
        if isinstance(x, list):
            return [clip(v, per) for v in x]
        if isinstance(x, str):
            return clamp(x, per)
        return x

    per = max(120, budget // 2)
    for _ in range(24):
        trimmed = clip(obj, per)
        if len(json.dumps(trimmed, ensure_ascii=False)) <= budget:
            return trimmed, True
        if per <= 60:
            break
        per = int(per * 0.6)

    hard = {}
    for k, v in obj.items():
        if isinstance(v, str):
            hard[k] = v[:40] + ('…' if len(v) > 40 else '')
        elif isinstance(v, (int, float, bool)) or v is None:
            hard[k] = v
        elif isinstance(v, list):
            hard[k] = [i[:40] if isinstance(i, str) else i for i in v[:20]]
        elif isinstance(v, dict):
            hard[k] = {kk: (vv[:40] if isinstance(vv, str) else vv)
                       for kk, vv in list(v.items())[:20]}
        else:
            hard[k] = str(v)[:40]
    if len(json.dumps(hard, ensure_ascii=False)) <= budget:
        return hard, True
    # Keep the schema, drop the payload.
    return {k: ('' if isinstance(v, str) else ([] if isinstance(v, list) else {}))
            for k, v in obj.items()}, True


def blocks_text(blocks):
    texts, images = [], []
    for b in blocks or []:
        if not isinstance(b, dict):
            continue
        if b.get('type') in ('text', 'reasoning') and b.get('text'):
            texts.append(b['text'])
        elif b.get('type') == 'image':
            images.append(b.get('attachment') or {})
    return '\n'.join(texts), images


def image_note(att, media_dir):
    """Images live outside the transcript; leave a pointer to the extracted file."""
    aid = (att.get('attachmentId') or '').replace('sha256:', '')
    ext = 'png' if (att.get('mediaType') or '').endswith('png') else 'jpg'
    return '[image: %s %sx%s %s bytes — original file %s]' % (
        att.get('name') or 'image', att.get('width'), att.get('height'), att.get('bytes'),
        os.path.join(media_dir, '%s.%s' % (aid, ext)))


# ── conversion ──────────────────────────────────────────────────────────────
class Converter:
    """Turns a DSH export into ZCode (message, part) rows.

    The transcript is rebuilt from the events the export still treats as live:
    anything a compaction summary or prune superseded is skipped, and everything
    else is replayed in order. Only `user` carriers become human turns; the
    synthetic ones become model-only notices, which is what ZCode does with its
    own equivalents.
    """

    def __init__(self, events, *, session_id, project_id, cwd, provider, model,
                 fidelity='balanced', start_sequence=0, base_time=None,
                 keep_reasoning=False, media_dir=''):
        self.events = events
        self.session_id = session_id
        self.project_id = project_id
        self.cwd = cwd
        self.provider = provider
        self.model = model
        self.media_dir = media_dir

        (self.tail_n, self.h_args, self.h_out, self.h_text, self.h_reason,
         self.t_args, self.t_out, self.t_text, self.t_reason,
         self.err_out, self.synth_cap) = PRESETS[fidelity]
        if not keep_reasoning:
            # Imported thinking blocks carry no provider signature, and a
            # signature-less thinking block invalidates the next request.
            self.h_reason = self.t_reason = 0

        audit = live.audit(events)
        self.audit = audit
        self.live = audit['live']
        self.results = audit['results_by_call']
        self.compactions = live.compaction_records(events)
        self.checkpoint = next((e for e in self.live
                                if e['type'] == 'user/message'
                                and ((e['data'].get('source') or {}).get('kind')) == 'compact-checkpoint'),
                               None)

        step_ids, seen = [], set()
        for e in self.live:
            if e['type'] != 'assistant/message':
                continue
            d = e['data']
            k = (d.get('turn'), d.get('step'))
            if k not in seen:
                seen.add(k)
                step_ids.append(k)
        self.step_order = step_ids
        self.recent = set(step_ids[max(0, len(step_ids) - self.tail_n):])

        times = [e['time'] for e in self.live if 'time' in e] or [0, 1]
        self.tmin, self.tmax = min(times), max(times)
        self.base_time = base_time if base_time is not None else int(time.time() * 1000)
        self.scale = (120_000 / (self.tmax - self.tmin)) if self.tmax > self.tmin else 0.0

        self.start_sequence = start_sequence
        self.rows = []
        self._last_t = self.base_time
        self.stats = collections.Counter()

    # -- scaffolding --------------------------------------------------------
    def _stamp(self, t):
        t = max(t, self._last_t + 10)
        self._last_t = t
        return t

    def _remap(self, t):
        return self.base_time + int((t - self.tmin) * self.scale)

    def _user_data(self, text, kind, created, turn):
        sem = KIND_SEMANTICS.get(kind, KIND_SEMANTICS['user'])
        data = {
            'role': 'user',
            'time': {'created': created},
            'agent': 'zcode-agent',
            'semantics': {'origin': sem['origin'], 'kind': sem['kind'],
                          'uiVisibility': sem['ui'],
                          'providerVisibility': sem['provider'],
                          'transcriptVisibility': sem['transcript']},
            'anchor': {'turnId': turn,
                       'origin': 'realUser' if kind == 'user' else 'synthetic'},
            'tools': {name: True for name in tmap.ZCODE_TOOLS},
            'metadata': {
                'source': 'user' if kind == 'user' else 'dsh-import',
                'visibility': 'default' if kind == 'user' else 'model-only',
                'inputIntent': {
                    'sourceCommandId': str(uuid.uuid4()),
                    'queueItemId': 'queue_imp_%s' % common._tok(6),
                    'clientId': 'client-dsh-import',
                    'kind': 'sendText',
                    'text': text[:400],
                    'modelSelection': {'providerId': self.provider, 'modelId': self.model,
                                       'options': {'reasoningLevel': 'enabled'}},
                    'mode': 'yolo', 'planEnabled': False,
                    'admissionSeq': self.start_sequence, 'admittedAt': created,
                    'requestedDelivery': 'startNow', 'admittedDelivery': 'startNow',
                    'attachmentRefs': [],
                },
                'inputClientId': 'client-dsh-import',
            },
            'model': {'providerID': self.provider, 'modelID': self.model, 'variant': 'enabled'},
        }
        if kind == 'user':
            data['modelSelection'] = {'providerId': self.provider, 'modelId': self.model,
                                      'options': {'reasoningLevel': 'enabled'}}
            data['contextSnapshot'] = {'envInfo': dict(ENV_INFO, cwd=self.cwd)}
        else:
            data['synthetic'] = True
        return data

    def _user_row(self, text, kind, ts, turn):
        mid = common.new_message_id()
        created = self._stamp(ts)
        data = self._user_data(text, kind, created, turn)
        parts = [{'type': 'text', 'text': text, 'time': {'start': created, 'end': created}}]
        if kind == 'compact-checkpoint':
            inner = text
            if '<compacted-summary>' in text:
                inner = text.split('<compacted-summary>', 1)[1].split('</compacted-summary>', 1)[0]
            data['summary'] = {'title': 'Compact summary', 'body': inner.strip()}
            parts.append({'type': 'compaction', 'auto': True, 'trigger': 'auto',
                          'phase': 'mid_turn', 'compactReason': 'context_limit',
                          'operationId': 'cmp_imp_%s' % common._tok(8),
                          'timelineStatus': 'completed', 'timelineDisplay': 'separator',
                          'replace': True, 'summaryMessageId': mid})
        self.rows.append([mid, None, created, data, parts])
        self.stats['messages'] += 1
        return mid

    def _assistant_row(self, event, parent, turn):
        d = event['data']
        key = (d.get('turn'), d.get('step'))
        recent = key in self.recent
        created = self._stamp(self._remap(event['time']))
        body = d.get('message') or {}
        content = body.get('content') or []

        texts, reasons = [], []
        for b in content:
            if not isinstance(b, dict):
                continue
            if b.get('type') == 'text' and (b.get('text') or '').strip():
                texts.append(b['text'])
            elif b.get('type') == 'reasoning' and (b.get('text') or '').strip():
                reasons.append(b['text'])

        parts = [{'type': 'step-start'}]
        cap = self.t_reason if recent else self.h_reason
        if reasons and cap:
            joined = clamp('\n'.join(reasons), cap)
            if joined:
                parts.append({'type': 'reasoning', 'text': joined,
                              'metadata': {'imported': True,
                                           'note': 'reasoning text carried from DeepSeek Harness'},
                              'time': {'start': created, 'end': created}})
                self.stats['reasoning_chars'] += len(joined)
        if texts:
            cap = self.t_text if recent else self.h_text
            joined = clamp('\n'.join(texts), cap)
            parts.append({'type': 'text', 'text': joined,
                          'time': {'start': created, 'end': created}})
            self.stats['text_chars'] += len(joined)

        calls = live.tool_calls_of(event)
        for i, c in enumerate(calls):
            cid = c.get('id')
            zname = tmap.map_tool(c.get('name'))
            raw = c.get('arguments') or '{}'
            try:
                parsed = json.loads(raw) if isinstance(raw, str) else raw
                if not isinstance(parsed, dict):
                    parsed = {'value': parsed}
            except Exception:
                parsed = {'_raw': str(raw)[:2000]}
            parsed = tmap.fix_args(zname, parsed)
            capped, was_trunc = shrink_input(parsed, self.t_args if recent else self.h_args)

            st = {'status': 'completed', 'input': capped,
                  'time': {'start': created, 'end': created}}
            r = self.results.get(cid)
            if r is None:
                # ZCode has no "call without result" state; the transcript the
                # provider replays must pair every call, so record it as empty.
                st['output'] = ''
            else:
                out, imgs = blocks_text((r.get('data', {}).get('message') or {}).get('content'))
                if imgs:
                    note = '\n'.join(image_note(x, self.media_dir) for x in imgs)
                    out = (out + '\n' if out else '') + note
                rd = r.get('data') or {}
                if (rd.get('message') or {}).get('isError') or rd.get('error'):
                    st['status'] = 'error'
                    st['error'] = (clamp(out, self.err_out)
                                   or json.dumps(rd.get('error'), ensure_ascii=False)[:self.err_out]
                                   or 'tool failed')
                    st['metadata'] = {}
                    self.stats['tool_errors'] += 1
                else:
                    out_cap = self.t_out if recent else self.h_out
                    stub = STUB_TOOLS.get(zname)
                    if stub and not recent:
                        out_cap = min(out_cap, stub)
                    clipped = clamp(out, out_cap)
                    st['output'] = clipped
                    st['metadata'] = {'schemaVersion': 1, 'serialization': {
                        'truncated': len(out) > out_cap,
                        'originalBytes': len(out.encode('utf-8')),
                        'returnedBytes': len(clipped.encode('utf-8')),
                        'budgetStrategy': 'artifact'}}
                    self.stats['tool_output_chars'] += len(clipped)
            if st['status'] == 'completed':
                st['title'] = zname
            if c.get('name') and c['name'] != zname:
                st['metadata'] = dict(st.get('metadata') or {}, dshToolName=c['name'])
            if was_trunc:
                st.setdefault('metadata', {})['inputTruncated'] = True
            self.stats['tool_args_chars'] += len(json.dumps(capped, ensure_ascii=False))
            self.stats['tool_calls'] += 1
            parts.append({'type': 'tool', 'callID': cid, 'declarationIndex': i,
                          'tool': zname, 'state': st})

        finish = 'tool-calls' if calls else 'stop'
        parts.append({'type': 'step-finish', 'reason': finish, 'cost': 0,
                      'tokens': {'total': 0, 'input': 0, 'output': 0, 'reasoning': 0,
                                 'cache': {'read': 0, 'write': 0}}})
        data = {
            'role': 'assistant',
            'time': {'created': created, 'completed': created},
            'parentID': parent,
            'modelId': self.model, 'providerId': self.provider,
            'mode': 'yolo', 'planEnabled': False, 'agent': 'zcode-agent',
            'path': {'cwd': self.cwd, 'root': self.cwd},
            'cost': 0,
            'tokens': {'total': 0, 'input': 0, 'output': 0, 'reasoning': 0,
                       'cache': {'read': 0, 'write': 0}},
            'finish': finish,
            'semantics': {'origin': 'agent_runtime', 'kind': 'assistant_response',
                          'uiVisibility': 'visible', 'providerVisibility': 'visible',
                          'transcriptVisibility': 'visible'},
            'anchor': {'turnId': turn},
        }
        mid = common.new_message_id()
        self.rows.append([mid, None, created, data, parts])
        self.stats['messages'] += 1
        return mid

    # -- driver -------------------------------------------------------------
    def build(self):
        turn = common.new_turn_id()
        parent = None
        for e in self.live:
            et = e['type']
            d = e.get('data') or {}
            if et == 'user/message':
                kind = (d.get('source') or {}).get('kind')
                if kind not in IMPORT_USER_KINDS and kind != 'compact-checkpoint':
                    self.stats['skipped_' + str(kind)] += 1
                    continue
                txt = '\n'.join(b.get('text') or '' for b in d.get('content') or []
                                if isinstance(b, dict) and b.get('type') == 'text')
                if not txt.strip():
                    continue
                if kind == 'user':
                    # a real prompt always starts its own turn
                    turn = common.new_turn_id()
                elif parent is None:
                    turn = common.new_turn_id()
                if kind != 'user':
                    txt = '[%s]\n%s' % (kind, clamp(txt, self.synth_cap))
                parent = self._user_row(txt, kind, self._remap(e['time']), turn)
            elif et == 'assistant/message':
                if parent is None:
                    turn = common.new_turn_id()
                    parent = self._user_row('[continuing session]', 'user',
                                            self._remap(e['time']), turn)
                self._assistant_row(e, parent, turn)

        seq = self.start_sequence
        out = []
        for mid, _, created, data, parts in self.rows:
            out.append((mid, seq, created, json.dumps(data, ensure_ascii=False), parts))
            seq += 1
        self.rows = out
        return out

    # -- reporting ----------------------------------------------------------
    def size_report(self):
        blob = ''.join(json.dumps(p, ensure_ascii=False) for _, _, _, _, parts in self.rows
                       for p in parts)
        cjk = len(re.findall(r'[\u3000-\u9fff\uff00-\uffef]', blob))
        stored = sum(len(dj) for _, _, _, dj, _ in self.rows) + len(blob)
        return {
            'messages': len(self.rows),
            'parts': sum(len(p) for _, _, _, _, p in self.rows),
            'tool_calls': self.stats['tool_calls'],
            'tool_errors': self.stats['tool_errors'],
            'stored_chars': stored,
            # Chinese costs about one token per character; ASCII about 0.28.
            'tokens': int(cjk + (len(blob) - cjk) * 0.28),
        }


# ── writing ─────────────────────────────────────────────────────────────────
def write_rows(db, session_id, rows, *, new_session=None, title=None):
    con = common.connect(db)
    n_parts = sum(len(p) for _, _, _, _, p in rows)
    try:
        cur = con.cursor()
        cur.execute('begin immediate')
        if new_session:
            cols = ', '.join(new_session)
            marks = ', '.join('?' for _ in new_session)
            cur.execute('insert into session (%s) values (%s)' % (cols, marks),
                        tuple(new_session.values()))
        for mid, seq, created, dj, parts in rows:
            cur.execute('insert into message (id, session_id, time_created, time_updated, data, sequence) '
                        'values (?,?,?,?,?,?)', (mid, session_id, created, created, dj, seq))
            for i, p in enumerate(parts):
                cur.execute('insert into part (id, message_id, session_id, time_created, '
                            'time_updated, data, sequence) values (?,?,?,?,?,?,?)',
                            (common.new_part_id(), mid, session_id, created, created,
                             json.dumps(p, ensure_ascii=False), i))
        if title:
            now = int(time.time() * 1000)
            cur.execute('update session set time_updated=?, title=?, title_source=?, '
                        'time_title_updated=? where id=?',
                        (now, title, 'custom', now, session_id))
        con.commit()
    except Exception:
        con.rollback()
        raise
    finally:
        con.close()
    return len(rows), n_parts


def add_input_history(db, session_id, project_id, prompts):
    """Make the imported prompts reachable from the composer's recall list."""
    if not prompts:
        return 0
    con = common.connect(db)
    try:
        existing = {r[0] for r in con.execute(
            'select text from input_history where session_id=?', (session_id,))}
        base = int(time.time() * 1000)
        added = 0
        cur = con.cursor()
        cur.execute('begin immediate')
        for i, text in enumerate(prompts):
            if not text.strip() or text in existing:
                continue
            cur.execute('insert into input_history (id, project_id, session_id, text, kind, '
                        'time_created, attachments) values (?,?,?,?,?,?,?)',
                        ('input_imp_%s' % uuid.uuid4(), project_id, session_id, text,
                         'prompt', base + i * 1000, None))
            added += 1
        con.commit()
    except Exception:
        con.rollback()
        raise
    finally:
        con.close()
    return added


def rollback(db, session_id, purge_backup=None):
    """Delete imported rows, or restore a snapshot when purge_backup is given."""
    if purge_backup:
        con = common.connect(db)
        try:
            with con:
                con.execute('attach database ? as bak', (purge_backup,))
                con.execute('delete from message where session_id=?', (session_id,))
                con.execute('insert into message select * from bak.message where session_id=?',
                            (session_id,))
                con.execute('delete from part where session_id=?', (session_id,))
                con.execute('insert into part select * from bak.part where session_id=?',
                            (session_id,))
                con.execute('detach database bak')
        finally:
            con.close()
        return 'restored from %s' % purge_backup

    con = common.connect(db)
    try:
        with con:
            cur = con.cursor()
            np = cur.execute("select count(*) from part where session_id=? and message_id like 'msg_mig%'",
                             (session_id,)).fetchone()[0]
            nm = cur.execute("select count(*) from message where session_id=? and id like 'msg_mig%'",
                             (session_id,)).fetchone()[0]
            cur.execute("delete from part where session_id=? and message_id like 'msg_mig%'", (session_id,))
            cur.execute("delete from message where session_id=? and id like 'msg_mig%'", (session_id,))
            cur.execute("delete from input_history where session_id=? and id like 'input_imp_%'",
                        (session_id,))
    finally:
        con.close()
    return 'removed %d messages / %d parts' % (nm, np)


def list_backups(db):
    parent = os.path.dirname(db)
    return sorted(d for d in os.listdir(parent)
                  if d.startswith('_') and '-backup-' in d
                  and os.path.isdir(os.path.join(parent, d)))


def _zcode_running():
    try:
        import subprocess
        out = subprocess.run(['tasklist', '/fi', 'imagename eq ZCode.exe', '/nh'],
                             capture_output=True, text=True, timeout=15).stdout
        return sum(1 for line in out.splitlines() if 'ZCode.exe' in line)
    except Exception:
        return 0


# ── commands ────────────────────────────────────────────────────────────────
def cmd_inspect(args):
    events, src = common.load_export(args.export, args.extract_to)
    meta = common.export_meta(events)
    counts, tools = common.summarize_export(events)
    prompts = common.list_user_prompts(events)
    audit = live.audit(events)
    comps = live.compaction_records(events)

    print('source               ', src)
    print('export session id    ', meta['session_id'])
    print('cwd                  ', meta['cwd'])
    print('events in file       ', len(events))
    print('successful compactions', len(comps))
    for c in comps:
        d = c['data']
        print('   seq %-5s shadowed %4d events' % (c['seq'], len(d.get('shadowedSeqs') or [])))
    print('prune records        ', sum(1 for e in events if e['type'] == 'compaction/prune'))
    print()
    print('live conversation     ', audit['live_events'], audit['by_type'])
    print('live seq range        ', audit['seq_range'])
    print('live events below the last compaction:', audit['live_below_last_summary'])
    print('human turns           ', audit['human_turns'])
    print('tool calls / results  ', audit['calls'], '/', audit['results'],
          '| unpaired', len(audit['calls_without_result']) + len(audit['results_without_call']))
    print()
    print('all tool calls in file', sum(tools.values()), dict(tools.most_common()))
    print()
    print('first prompts in file (may be superseded):')
    for p in prompts[:6]:
        print('   [%5s] %s' % (p['seq'], p['text'].replace('\n', ' ')[:100]))
    subs = os.path.join(src, common.EXPORT_SUBAGENTS)
    if os.path.isdir(subs):
        n = sum(1 for d in os.listdir(subs)
                if os.path.exists(os.path.join(subs, d, common.EXPORT_MAIN)))
        print()
        print('subagent logs         ', n, '(not imported; each is its own session)')
    return 0


def cmd_convert(args):
    events, src = common.load_export(args.export, args.extract_to)
    meta = common.export_meta(events)
    db = args.db
    cwd = args.cwd or meta['cwd'] or os.getcwd()

    if not os.path.exists(db):
        raise SystemExit('ZCode database not found: %s' % db)

    if args.session:
        row = common.session_row(db, args.session)
        if row is None:
            raise SystemExit('no such session: %s' % args.session)
        session_id = row['id']
        project_id = row['project_id']
        cwd = args.cwd or row['directory'] or cwd
        title = args.title or ('%s · resumed from DSH' % row['title'])
        con = common.connect(db, readonly=True)
        try:
            ex = con.execute('select count(*) n, coalesce(max(sequence),-1) mx, '
                             'coalesce(max(time_created),0) mt from message where session_id=?',
                             (session_id,)).fetchone()
        finally:
            con.close()
        start_seq = ex['mx'] + 1
        base_time = ex['mt'] + 1000
        new_session = None
    else:
        if not args.new_session:
            raise SystemExit('pass --session <id> to append, or --new-session to create one')
        session_id = common.new_session_id()
        project_id = common.project_id_for(cwd)
        title = args.title or 'imported · DSH session'
        start_seq = 0
        base_time = int(time.time() * 1000)
        new_session = {
            'id': session_id, 'project_id': project_id, 'slug': session_id,
            'directory': cwd, 'path': cwd, 'title': title, 'version': '0.16.9',
            'permission': '{"mode":"yolo"}', 'time_created': base_time,
            'time_updated': base_time, 'task_type': 'interactive',
            'title_source': 'custom', 'trace_id': str(uuid.uuid4()),
        }

    conv = Converter(events, session_id=session_id, project_id=project_id, cwd=cwd,
                     provider=args.provider, model=args.model, fidelity=args.fidelity,
                     start_sequence=start_seq, base_time=base_time,
                     keep_reasoning=args.keep_reasoning,
                     media_dir=os.path.join(src, 'media'))
    rows = conv.build()
    rep = conv.size_report()

    print('export                ', src)
    print('fidelity              ', args.fidelity)
    print('target session        ', session_id, '(new)' if new_session else '')
    print('cwd                   ', cwd)
    print('provider/model        ', '%s/%s' % (args.provider, args.model))
    print('live conversation     ', conv.audit['live_events'], 'events from',
          conv.audit['seq_range'])
    print('human turns           ', conv.audit['human_turns'])
    print('messages to insert    ', rep['messages'])
    print('parts to insert       ', rep['parts'], '(%d tool calls, %d errors)'
          % (rep['tool_calls'], rep['tool_errors']))
    print('stored chars          ', rep['stored_chars'])
    print('estimated tokens      ', rep['tokens'])
    if conv.stats:
        skipped = {k[8:]: v for k, v in conv.stats.items() if k.startswith('skipped_')}
        if skipped:
            print('skipped carriers      ', skipped)

    preview = []
    for mid, seq, created, dj, parts in rows[:4] + rows[-3:]:
        d = json.loads(dj)
        preview.append('--- %s seq=%s role=%s finish=%s parts=%d'
                       % (mid, seq, d.get('role'), d.get('finish'), len(parts)))
        for p in parts:
            t = p['type']
            if t in ('text', 'reasoning'):
                preview.append('    %s: %s' % (t, p['text'][:300].replace('\n', '\\n')))
            elif t == 'tool':
                preview.append('    tool %s status=%s input=%s'
                               % (p['tool'], p['state']['status'],
                                  json.dumps(p['state'].get('input'), ensure_ascii=False)[:260]))
                for k in ('output', 'error'):
                    if p['state'].get(k):
                        preview.append('      %s: %s' % (k, p['state'][k][:200].replace('\n', '\\n')))
    if args.out_dir:
        os.makedirs(args.out_dir, exist_ok=True)
        with open(os.path.join(args.out_dir, 'preview.txt'), 'w', encoding='utf-8') as f:
            f.write('\n'.join(preview))
        print('preview               ', os.path.join(args.out_dir, 'preview.txt'))

    if not args.commit:
        print('\nDRY RUN — nothing written. Re-run with --commit to apply.')
        return 0

    running = _zcode_running()
    if running and not args.force:
        raise SystemExit('ZCode is running (%d processes). Close it, or pass --force.' % running)

    backup = common.backup_db(db, tag='import')
    print('backup                ', backup)
    n, np = write_rows(db, session_id, rows, new_session=new_session, title=title)
    prompts = [p['text'] for p in common.list_user_prompts(events)]
    added = 0 if args.no_history else add_input_history(db, session_id, project_id, prompts)
    print('committed             %d messages / %d parts' % (n, np))
    print('input history         %d prompts' % added)
    return 0


def cmd_verify(args):
    db = args.db
    sid = args.session
    con = common.connect(db, readonly=True)
    try:
        integ = con.execute('pragma quick_check').fetchone()[0]
        fk = con.execute('pragma foreign_key_check').fetchall()
        msgs = con.execute('select id, sequence, data from message where session_id=? '
                           'order by sequence', (sid,)).fetchall()
        if not msgs:
            raise SystemExit('no messages for session: %s' % sid)
        parts = collections.defaultdict(list)
        for r in con.execute('select message_id, sequence, data from part where session_id=? '
                             'order by message_id, sequence', (sid,)):
            parts[r['message_id']].append((r['sequence'], json.loads(r['data'])))

        part_shapes, state_shapes, msg_shapes = common.native_shapes(db)
        problems = []
        seqs = [m['sequence'] for m in msgs]
        if seqs != list(range(seqs[0], seqs[0] + len(seqs))):
            dupes = [s for s, n in collections.Counter(seqs).items() if n > 1]
            gaps = [s for s in range(seqs[0], seqs[-1] + 1) if s not in set(seqs)]
            problems.append('message sequences not contiguous (gaps=%s dupes=%s)' % (gaps[:5], dupes[:5]))

        ids = {m['id'] for m in msgs}
        for m in msgs:
            d = json.loads(m['data'])
            extra = set(d.keys()) - msg_shapes
            if extra:
                problems.append('seq %s: message keys outside native set: %s'
                                % (m['sequence'], sorted(extra)))
            p = d.get('parentID')
            if p and p not in ids:
                problems.append('seq %s: dangling parentID' % m['sequence'])
            kinds = [o.get('type') for _, o in parts[m['id']]]
            if d.get('role') == 'assistant' and 'timeline' not in kinds:
                if not kinds or kinds[0] != 'step-start' or kinds[-1] != 'step-finish':
                    problems.append('seq %s: assistant part order %s' % (m['sequence'], kinds[:4]))
                ntool = kinds.count('tool')
                if (d.get('finish') == 'tool-calls') != (ntool > 0):
                    problems.append('seq %s: finish=%s with %d tool parts'
                                    % (m['sequence'], d.get('finish'), ntool))
            if [s for s, _ in parts[m['id']]] != list(range(len(parts[m['id']]))):
                problems.append('seq %s: part sequence not 0..n-1' % m['sequence'])

        for mid, lst in parts.items():
            for _, o in lst:
                t = o.get('type')
                if t not in part_shapes:
                    problems.append('%s: unknown part type %s' % (mid, t))
                    continue
                extra = set(o.keys()) - part_shapes[t]
                if extra:
                    problems.append('%s: part keys outside native set: %s' % (mid, sorted(extra)))
                if t == 'tool':
                    st = o.get('state') or {}
                    s = st.get('status')
                    allowed = state_shapes.get(s)
                    if allowed is None:
                        problems.append('%s: unknown tool status %s' % (mid, s))
                    else:
                        se = set(st.keys()) - allowed
                        if se:
                            problems.append('%s: tool state keys outside native set: %s'
                                            % (mid, sorted(se)))
                        if 'input' not in st:
                            problems.append('%s: tool state without input' % mid)
                    if not o.get('callID'):
                        problems.append('%s: tool part without callID' % mid)

        dupe_calls = [c for c, n in collections.Counter(
            o['callID'] for lst in parts.values() for _, o in lst
            if o.get('type') == 'tool').items() if n > 1]

        print('session               ', sid)
        print('integrity             ', integ, '| foreign keys', 'clean' if not fk else fk[:2])
        print('messages              ', len(msgs), '| parts', sum(len(v) for v in parts.values()))
        print('imported by this tool ', sum(1 for m in msgs if m['id'].startswith('msg_mig')))
        print('duplicate callIDs     ', len(dupe_calls))
        print('problems              ', len(problems))
        for p in problems[: args.max_problems]:
            print('   ', p)
        return 1 if problems else 0
    finally:
        con.close()


def cmd_rollback(args):
    db = args.db
    if args.list_backups:
        for b in list_backups(db):
            print(b)
        return 0
    if not args.session:
        raise SystemExit('--session is required (or use --list-backups)')
    if args.purge:
        backups = list_backups(db)
        if not backups:
            raise SystemExit('no backups next to %s' % db)
        target = args.purge if args.purge != 'latest' else backups[-1]
        path = target if os.path.sep in target else os.path.join(os.path.dirname(db), target)
        if not os.path.exists(path):
            raise SystemExit('backup not found: %s' % path)
        print(rollback(db, args.session, purge_backup=path))
    else:
        print(rollback(db, args.session))
    return 0


# ── cli ─────────────────────────────────────────────────────────────────────
def build_parser():
    p = argparse.ArgumentParser(
        prog='zcode_migrate.py',
        description='Import a DeepSeek Harness session export into a ZCode profile.',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog='Every command is read-only unless --commit or --purge is given.')
    p.add_argument('--db', default=common.DEFAULT_DB, help='ZCode db.sqlite (default: %(default)s)')
    sub = p.add_subparsers(dest='cmd', required=True)

    i = sub.add_parser('inspect', help='describe an export without touching the database')
    i.add_argument('export', help='DSH export .zip or an extracted directory')
    i.add_argument('--extract-to', help='where to unpack a .zip (default: beside it)')
    i.set_defaults(func=cmd_inspect)

    c = sub.add_parser('convert', help='convert an export into message/part rows')
    c.add_argument('export')
    c.add_argument('--session', help='existing ZCode session id to append to')
    c.add_argument('--new-session', action='store_true', help='create a fresh session instead')
    c.add_argument('--cwd', help='workspace path recorded on the rows (default: export cwd)')
    c.add_argument('--provider', default='new-provider-3')
    c.add_argument('--model', default='gpt-6-luna')
    c.add_argument('--fidelity', default='balanced', choices=sorted(PRESETS))
    c.add_argument('--title', help='session title to set')
    c.add_argument('--extract-to')
    c.add_argument('--out-dir', help='directory for preview.txt')
    c.add_argument('--keep-reasoning', action='store_true',
                   help='import thinking text (unsigned; can break the next request)')
    c.add_argument('--no-history', action='store_true', help='skip input_history backfill')
    c.add_argument('--commit', action='store_true', help='actually write')
    c.add_argument('--force', action='store_true', help='write even while ZCode is running')
    c.set_defaults(func=cmd_convert)

    v = sub.add_parser('verify', help='check a session against the shapes native rows use')
    v.add_argument('session')
    v.add_argument('--max-problems', type=int, default=20)
    v.set_defaults(func=cmd_verify)

    r = sub.add_parser('rollback', help='remove imported rows, or restore a backup')
    r.add_argument('session', nargs='?')
    r.add_argument('--purge', nargs='?', const='latest',
                   help='restore this session from a backup directory (default: latest)')
    r.add_argument('--list-backups', action='store_true')
    r.set_defaults(func=cmd_rollback)
    return p


def main(argv=None):
    args = build_parser().parse_args(argv)
    return args.func(args)


if __name__ == '__main__':
    sys.exit(main())
